Refactor GitHub Actions workflow for Go project

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -5,9 +5,9 @@ env:
 
 on:
   push:
-    branches: ["main"]
+    branches: [ "main" ]
   pull_request:
-    branches: ["main"]
+    branches: [ "main" ]
 
 jobs:
   build:
@@ -17,52 +17,33 @@ jobs:
       checks: write
 
     steps:
-      - uses: actions/checkout@v3
+    - uses: actions/checkout@v3
 
-      - name: Set up Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: "1.20.x"
-          cache: true
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version-file: 'go.mod'
+        cache: true
 
+    - name: Revive Action
+      uses: morphy2k/revive-action@v2.4.1
 
-      - name: Revive Action
-        uses: morphy2k/revive-action@v2.4.1
-      - name: Debug staticcheck (print output)
-        run: |
-          go env
-          go version
-          go install honnef.co/go/tools/cmd/staticcheck@latest
-          $(go env GOPATH)/bin/staticcheck -version
-          $(go env GOPATH)/bin/staticcheck ./...
+    - name: Staticcheck
+      uses: dominikh/staticcheck-action@v1.3.0
 
-      - name: Staticcheck
-        uses: dominikh/staticcheck-action@v1.3.0
-        with:
-          install-go: false
-          version: "2023.1.7"          
+    - name: Build
+      run: |
+        go mod download
+        go install gotest.tools/gotestsum@latest
 
-      - name: Build
-        run: |
-          go mod download
-          go install gotest.tools/gotestsum@latest
-          go install github.com/jstemmer/go-junit-report/v2@latest
+    - name: Test
+      run: |
+        gotestsum --format=standard-verbose --junitfile=junit.xml
 
-      - name: Test
-        run: |
-          gotestsum --format=standard-verbose --junitfile=junit.xml ./...
-          #go test ./... -v 2>&1 | go-junit-report -set-exit-code > junit.xml
-          
-      - name: List reports
-        if: success() || failure()
-        run: |
-          ls -la
-          find . -maxdepth 3 -name "*.xml" -print
-          
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v3
-        if: success() || failure()
-        with:
-          report_paths: "junit.xml"
-          detailed_summary: true
-          include_passed: true
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
